### ISSUE TITLE
Add GitHub `hub` Tool Integration

### ISSUE THREAD

**Issue by raamdev** [websharks/hubflow#7]
The GitHub [`hub`](http://hub.github.com) tool can make some of our workflow easier, by allowing us to submit Pull Requests directly from the command line, for example.

What kinds of things can `hub` do that we'd like to see possible inside our current Hubflow workflow?

**Comment by jaswsinc** [comment]
I just reviewed the docs here again: https://github.com/github/hub

There are many useful shortcuts made possible by this tool. For the most part, things that serve as time-savers when the repos that you work on are all associated with GitHub remotes. So IMO, the biggest benefit to having this tool is the shortcuts it provides. Less typing = cool!

Among the functionality provided by Hub is the ability to create new repos, spawn browser windows that lead to a specific repo, or to a specific issue; and the ability to open pull requests.

Since the PR functionality is already built into this tool (maintained by GitHub), and already useful in a number of ways to each of us individually; it seems easy enough to take advantage of the PR functionality that it provides in any custom tools that we write. That's all I've got though. In terms of how we might integrate Hub with our own set of flow-like tools, the `git pull-request` and `git browse` commands seem like the only ones that would be candidates for this.

**Comment by raamdev** [comment]
Cool, so it sounds like what we need is to figure out exactly what steps in our current Hubflow workflow could be further streamlined by integrating specific features of `hub`. Once we do that, I'll open GitHub Issues related to that work and get started on making that happen.

I've been researching `hub` for the past hour, trying it out and seeing how it might work for us. I'm going to start posting some important findings here on this issue just to get us started.

**Comment by raamdev** [comment]
## Hub Configuration

### Use SSH for Authentication

By default, `hub` will use the HTTPS protocol for authentication when you do things like `hub clone`. You'll want to use SSH. 

Set this  globally (note that the `ssh` option here requires `hub version 2.2.0-rc1-gd557166`):

```
git config --global hub.protocol ssh
```

See also: [docs on hub configuration](https://github.com/github/hub#configuration)

**Comment by raamdev** [comment]
I just ran some tests for what I see as a common development workflow. I also tested what I envision as potential improvements to the Hubflow project by utilizing the `hub` command to automate a few things:

### Start working on an new Feature Branch

A new GitHub Issue has been opened and work needs to start. Let's say we're working on GitHub Issue `#8`.

Using the workflow we discussed earlier where we use a Pull Request for an Issue to create a checklist of TODO items and discuss the issue (to keep that internal discussion separate from customer-facing discussion about a bug/feature), the step after creating the feature branch would be to create a Pull Request. However, that's not possible until we change something. 

Here's what this process might look like (all of this could be automated so that the `git hf feature start '#8'` does all of the stuff that follows that command below):

```
git hf feature start '#8'
echo "- @raamdev has started working on [#8](http://github.com/websharks/test-repo#8)" >> README.md
git add README.md
git commit -m "Starting work on Issue #8"
echo "Closes #8
>
> Closes issue #8" > pr.msg.tmp
hub pull-request --browse -F pr.msg.tmp
rm -f pr.msg.tmp
```

`hub pull-request --browse -F pr.msg.tmp` This step uses the Title/Body from the temp file created in the previous step to create the Pull Request, then it opens new Pull Request on GitHub in your browser so that you can fill out a checklist of TODO items.

Now we can start working on this issue, making changes, and doing commits. 

### Periodically commit work, and push to remote

```
git commit -m "Making some changes"
git push
```

### Merge Pull Request

When we're ready to merge the Pull Request (after changes have been reviewed, etc.), we run a single command:

```
git hf feature finish -f '#8'
```

#### What about the status we added to `README.md`?

If you remember, we added the following line to `README.md` when we created the feature branch and opened the Pull Request:

- @raamdev has started working on [#8](http://github.com/websharks/test-repo#8)

We have a few options here: We can remove the line entirely, then commit the changes to the `README.md` file before actually merging and closing the PR, or we can keep a sort of running long and append a new line:

- @raamdev has finished working on [#8](http://github.com/websharks/test-repo#8)

Whatever we decide, this extra step would be added to the `git hf feature finish -f '#8'` so that it happens before the PR is merged and closed.

### What this whole process would look like, fully automated

```
git hf feature start '#8'
# Browser would open to display newly-opened Pull Request
# Create a TODO checklist in the Pull Request body
#    or just call out a team member to begin internal discussion 
git commit -m "Making some changes"
git push
git hf feature finish -f '#8'
```

**Comment by jaswsinc** [comment]
Looks great to me! Wow, nice work on outlining this.

I don't have much more that I can add to this, but here are a couple ideas.

- In the final draft, the commit messages and the PR title could contain the full `[owner]/[repo]#[issue]` instead of just `#[issue]`. That way it works across a pro/lite repo if it needs to. I assume you already considered that, just wanted to mention it.

- We might create an iDoneThis `[ ]` TODO item when the PR is created. Maybe the `feature finish` could mark it as done. Not sure how that would work exactly, or if it's really ideal. Just came to mind as I was trying to think of anything else that could be automated by this.

**Comment by jaswsinc** [comment]
> This step uses the Title/Body from the temp file created in the previous step to create the Pull Request, then it opens new Pull Request on GitHub in your browser so that you can fill out a checklist of TODO items.

Great! That will be nice :-)

**Comment by raamdev** [comment]
> In the final draft, the commit messages and the PR title could contain the full [owner]/[repo]#[issue] instead of just #[issue]. That way it works across a pro/lite repo if it needs to. I assume you already considered that, just wanted to mention it.

Great idea! I had not thought of that, but that's definitely something we should add.

> We might create an iDoneThis [ ] TODO item when the PR is created. Maybe the feature finish could mark it as done. Not sure how that would work exactly, or if it's really ideal. Just came to mind as I was trying to think of anything else that could be automated by this

I'm not too psyched about that idea, but I'm open to suggestions. There's already a GitHub → iDoneThis integration that would add entries to iDoneThis, but maybe there is something specific that we'd like to add, perhaps something we usually add manually anyway (like `/done Reviewed and Merged Pull Request ABC for XYZ`).

Adding something to iDoneThis via a modified Hubflow tools would be easy if we make use of @brucewsinc's WS Commander `ws done` command. :)



> What about the status we added to README.md?

@jaswsinc What do you think we should do here? Just remove whatever we added to the `README.md` in that step (so that we had something to commit and open a PR)? Or do you think maintaining a running log would be useful? I'm thinking just removing the line from the README.md will be best, otherwise that will get cluttered rather quickly...

**Comment by jaswsinc** [comment]
> I'm not too psyched about that idea, but I'm open to suggestions.

I'm not either, now that I think about it. In fact, I've been thinking that we should disconnect the GitHub integration that we have with iDoneThis. The automated Dones are not at all what I was hoping to get from iDoneThis. I think the benefit of that service is that everything is in fact entered and recorded by each of us manually. Or, maybe we could work to limit the sort of Dones that GitHub pushes.

> What do you think we should do here? Just remove whatever we added to the README.md in that step (so that we had something to commit and open a PR)?

Yep. I think just removing this would be best. That would also help avoid a situation where somebody accidentally submits a PR with a single change; i.e. that line in the README. If we remove that from the README file then it shouldn't show up in the final diff either. At least in theory.

**Comment by raamdev** [comment]
Just noting here that instead of adding this PR functionality to hubflow itself, I added the following aliases to my `~/.bash_profile`:

```
alias fs='git hf feature start'
alias ff='git hf feature finish'
alias git-pr='git pull-request -b websharks:000000-dev'
```

So now my workflow looks like the following:

```
$ fs <issue-number> # starts a feature branch from `000000-dev`
# do work, commit
# do work, commit
$ git push
$ git-pr # I then enter the PR title and body in my commit message editor
# do any additional work, commit, push
$ ff -f # this merges the PR back into `000000-dev` and closes the PR on GitHub
```

----

This simplifies the workflow enough for me that I don't feel any desire for much less simplification. I like that I have control over the PR title and body when I open it (as opposed to having that always automated).

Since I think I'm the only one still using hubflow, I'm unassigning myself from this GitHub issue and considering it abandoned. @jaswsinc I'll leave it open unless you agree with abandoning it. :-)

**Comment by jaswsinc** [comment]
Abandoning this is fine with me also. I used Hubflow for quite a while whenever we got started with the Git workflow that this is designed for, but after a short time I found it easier to write my own aliases as you have, and then eventually I moved my aliases into custom scripts.

My feeling about Hubflow is that it's awesome. It's SO awesome and so helpful (i.e., because it deals with such a vital part of our workflow), that it becomes one of those things that inspires us to take things a step further. For me, I found it was worth my time to write custom scripts and at that point I moved away from Hubflow. Not because I didn't like it, but because Hubflow was more like a starting point for me.

I still think it's useful in that respect; e.g., we can still offer it up as a starting point for people who have not used anything like this before. They might stick with Hubflow as-is, or they might eventually write scripts of their own that do something similar but with little tweaks here and there.

With respect to the `hub` tool. My own personal scripts create a `.gitchange` file in the repo with a date-based counter in order to force a change. A PR is then opened automatically whenever I run `git fs <issue number>` so that starting a new feature branch also opens a PR for that work automatically.


```bash
date +'%s' > .gitchange;
```

... and then a bit further down...

```bash
pr_commit_message='Preparing pull request. See: '"${issue_ref}";
git commit --message="${pr_commit_message}" --no-edit;
git push --set-upstream origin "${feature}";

pr_title_body='PR: '"${feature}"$'\n\n';
pr_title_body+='See: '"${issue_ref}";

hub pull-request -m "${pr_title_body}" -h "${feature}" -b "${base}";
```

---

Here is my `git-feature-start` script. It's not self-contained, so it won't work as-is, because it currently relies upon some functions in my personal library. However, I'll post it here anyway in case it offers any inspiration for improvement here or at some point in the future.

```bash
#!/usr/bin/env bash

# Include strict mode & functions.

. ~/.bash/strict-mode;
. ~/.bash/functions;

# Include git repo requirements.

. ~/.bash/require-git-repo;
. ~/.bash/require-clean-git-repo;

# Intialize.

issue='';
base='';
feature='';
tree_dir='';

owner='';
slug='';
pr_commit_message='';
pr_title_body='';

# Parse options.

short_options='i:b:';
long_options='issue:,base:,base-branch:';
options="$(getopt --options "${short_options}" --longoptions "${long_options}" -- "${@}")";

eval set -- "${options}"; while true; do
	 case "${1}" in
			-i|--issue)
				issue="${2}";
				shift 2;
				;;
 			-b|--base|--base-branch)
 				base="${2}";
 				shift 2;
 				;;
			--) shift 1; break;
				;;
			*) echo 'Internal error.'; exit 1;
				;;
	 esac;
done;

if [[ -z "${issue}" && -n "${1:-}" ]]; then
	issue="${1}"; fi;

if [[ -z "${issue}" ]]; then
	issue="$(git-current-branch | grep --perl-regexp --ignore-case '^feature\/' | perl -wpe 's/^.+?\///ui' || true)";
fi;

if [[ -z "${base}" && -n "${2:-}" ]]; then
	base="${2}"; fi;

if [[ -z "${base}" ]]; then
	base='000000-dev'; fi;

feature='feature/'"${issue}";
tree_dir="$(git-tree-dir)";

# Validate options.

if [[ -z "${issue}" || ! "${issue}" =~ ^[1-9][0-9]*$ ]]; then
	echo 'Expecting a numeric issue number.';
	exit 1; # Error status.

elif [[ -z "${base}" ]] || ! git-branch-exists "${base}"; then
  echo 'There is no local `'"${base}"'` branch.';
  exit 1; # Error status.

elif ! git-remote-branch-exists "${base}"; then
  echo 'There is no remote `'"${base}"'` branch.';
  exit 1; # Error status.

elif git-branch-exists "${feature}"; then
  echo 'Local `'"${feature}"'` branch already exists.';
  exit 1; # Error status.

elif git-remote-branch-exists "${feature}"; then
  echo 'A remote `'"${feature}"'` branch already exists.';
  exit 1; # Error status.
fi;

# Start a new feature branch.
# `git fs [issue]` is the shortcut for this.

git checkout "${base}";
git pull origin "${base}";
git checkout -b "${feature}";

# If the the origin is located at GitHub, and we have the `hub` tool available.

if git-repo-has-github-origin && can-run hub; then

	# Piece-together some additional details.

  owner="$(git-repo-github-origin-parse owner)";
  slug="$(git-repo-github-origin-parse slug)";

  issue_url="$(git-github-issue-url "${owner}" "${slug}" "${issue}")";
  issue_ref="$(git-github-issue-ref "${owner}" "${slug}" "${issue}")";

  # Commit a change so that it's possible to open a pull request.

  date +'%s' > "${tree_dir}"/.gitchange;
	git add --all; # i.e., Stage the .gitchange file.

	pr_commit_message='Preparing pull request. See: '"${issue_ref}";
	git commit --message="${pr_commit_message}" --no-edit;

  # Push this branch to the remote now.

  git push --set-upstream origin "${feature}";

	# Open a pull request for this feature branch.

  pr_title_body='PR: '"${feature}"$'\n\n';
  pr_title_body+='See: '"${issue_ref}";

  hub pull-request -m "${pr_title_body}" -h "${feature}" -b "${base}";
fi;
```

**Comment by raamdev** [comment]
@jaswsinc Thanks for sharing that. :-) 

I see Hubflow as solving the problem that you just demonstrated above: maintaining a set of scripts for an entire team. If everybody is following the same workflow, as defined by the team lead(s), then what better way to enforce that workflow and than by having everyone on the team using the same thing (e.g., Hubflow) and running the same commands that produce the same series of actions? 

I realize that we decided _not_ to enforce anything workflow-wise, as long as a few key things happened (e.g., feature branches are called `feature/<issue-number>`) we didn't care how people got there. However, I think had Kristine and Renz been using Hubflow from the start, we could've all saved ourselves _a lot_ of time trying to explain this or that or helping them debug why their branch got out of date, etc. Of course that was a learning experience (for all of us), but it's certainly _not_ something that would scale to say, a dozen new developers on our team. 

Which is what I think Hubflow was created for in the first place: teams of developers. :-)

**Comment by jaswsinc** [comment]
I see your point and I agree.

On the other hand, there are minor personal preferences like whether to create a PR automatically or not. Also, from my personal viewpoint, I prefer to run custom scripts that contain commands I have written myself; using Hubflow as inspiration. That's not something that I'm really particular about, but if given the choice I almost always find myself more interested in writing a custom script, because it more closely resembles me; i.e., it's something that I have done myself and I can repeat it in the future. I'm not arguing that it's better, but it does make me feel better :-)

In the case of Hubflow, I found that easy to do, because the scripts that I wanted were short. Hubflow doesn't really introduce anything new in terms of functionality, it just automates a sequence of actions. In that respect, it's extremely useful. However, that automation can be achieved in a variety of ways once the concepts underlying them are understood; e.g., the Git branching model.

As for new team members, I'm not sure. I guess I look at Hubflow as being an abstraction that is going to be difficult for others to grasp if they don't understand (have experience with) the underlying Git commands that are being used in order to accomplish the operations being performed by Hubflow.

I guess it depends on what skill-level they are at when they start with us. If they are new to Git, then teaching them Hubflow first seems like it could add confusion, and perhaps distract them from learning Git commands first. I'm willing to give it a shot though. I just think it's easier to explain:

```bash
$ git checkout 000000-dev
$ git pull
$ git checkout -b feature/123
```

and work from there with someone new. There are little things that Hubflow does that make it a better approach, but those little things are hard to appreciate if you've haven't encountered them yourself by working with native Git commands and understanding the branching model from a pure Git perspective.

**Comment by jaswsinc** [comment]
I guess it would help to hear from @kristineds and @renz about this. What do you two think of Hubflow? Have you used it yet? If you were going to teach someone new about all that you've learned to do in Git thus far, do you think Hubflow would be a good starting point for them?

**Comment by renzms** [comment]
> What do you two think of Hubflow? Have you used it yet?

@jaswsinc  Have not used Hubflow, but I agree with you on this when teaching a new user who has never been on GitHub or used Git commands: 

>As for new team members, I'm not sure. I guess I look at Hubflow as being an abstraction that is going to be difficult for others to grasp if they don't understand (have experience with) the underlying Git commands that are being used in order to accomplish the operations being performed by Hubflow.

>I guess it depends on what skill-level they are at when they start with us. If they are new to Git, then teaching them Hubflow first seems like it could add confusion, and perhaps distract them from learning Git commands first. I'm willing to give it a shot though. I just think it's easier to explain:
```
$ git checkout 000000-dev
$ git pull
$ git checkout -b feature/123
```

I feel like knowing what does what and all the underlying code is important at the beginning. I prefer seeing and doing the bare bone git commands rather than having it automated. It makes me appreciate it more for what each command is and what it does, as well as learn things better as a "newbie". Moving forward though, if you feel it would make things easier on the team and the workflow if we all used Hubflow, then its up to you guys! :)

**Comment by jaswsinc** [comment]
@renzms writes...

> It makes me appreciate it more for what each
> command is and what it does, as well as learn things better

Thanks for sharing that. I can understand that completely. I think I would have felt the same. Having said that, you and Kristine are probably both ready to give HubFlow a shot, because I think both of you have been using Git long enough now to know how the branching model works, at least when it comes to feature branches, which represents most of what we use it for.


> Moving forward though, if you feel it would make things easier on the team and the workflow if we all used Hubflow, then its up to you guys! :)

Cool. Well, I'd give it a shot and see how you like it. It saves you some time and it sets a standard for the way that feature branches function in our Git workflow. Here's how to get started. It only takes a few minutes.

- Create a test repo in your own personal GitHub account.

- Clone that repo: `$ git clone https://github.com/[me]/[repo]`

- Create a dev branch: `$ git checkout -b 000000-dev`

- Push that dev branch: `$ git push --set-upstream origin 000000-dev`

- Install the HubFlow tool...

  - `$ brew tap websharks/formulas`
  - `$ brew install websharks-hubflow`

- Now initialize HubFlow while in that repo: `$ git hf init -af`

- Start a new feature branch and observe the magic.

  - `$ git hf feature start 123`

See also: https://github.com/websharks/hubflow
